name: CI Pipeline

# Grant write permissions to update repository contents.
permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Java with caching enabled (JDK 17)
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # Step 3: Build, Test, and Package the Application in One Command
      - name: Build and Test
        run: |
          echo "Building, testing, and packaging the project with Maven..."
          # The "verify" phase runs tests and packages the app.
          mvn clean verify -B

      # Step 4: Update Project Code (if needed)
      - name: Update Project Code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Making updates to the project code..."
          # Append the current date to update.log (force add since it’s in .gitignore)
          echo "Updated on $(date)" >> update.log
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f update.log
          git diff --cached --quiet || git commit -m "CI: Update project code with latest build log"
          git push origin HEAD:main

      # Step 5: Verification Step
      - name: Verification Step
        run: echo "CI workflow executed successfully!"

